In [9]:
import pandas as pd
url = 'https://drive.google.com/uc?id=1Mlu9r3afSGz5_02Y3wDJoQLpXszQXaIU'
df = pd.read_csv(url, index_col='order_id')
display(df.head())

          customer_name   product  quantity  unit_price  order_date     status
order_id
1001      Alice Johnson    Laptop       1.0     85000.0  2024-01-15  delivered
1002          Bob Smith     Mouse       3.0       499.0  2024-01-16    pending
1003        Carol White   Monitor       2.0     15000.0         NaN  delivered
1004         Dave Brown  Keyboard       NaN      1200.0  2024-01-18  cancelled
1005          Eva Green    Laptop       1.0     85000.0  2024-01-19  delivered

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 1001 to 1020
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_name  20 non-null     object
 1   product        20 non-null     object
 2   quantity       16 non-null     float64
 3   unit_price     20 non-null     float64
 4   order_date     16 non-null     object
 5   status         20 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.1+ KB

In [11]:
display(df.describe())

        quantity    unit_price
count  16.000000     20.000000
mean    2.437500  20224.600000
std     1.504161  33573.389607
min     1.000000    499.000000
25%     1.000000    799.000000
50%     2.000000   2500.000000
75%     3.000000  14625.000000
max     6.000000  85000.000000